-- Supabase Database Schema Script for DietWise
-- Run this script in the Supabase SQL Editor.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. BASE TABLES (No Foreign Key Dependencies)
-- =========================================================================

-- Recipes Global Library
CREATE TABLE IF NOT EXISTS public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    ingredients TEXT,
    instructions TEXT,
    calories INTEGER DEFAULT 0,
    protein_g INTEGER DEFAULT 0,
    carbs_g INTEGER DEFAULT 0,
    fats_g INTEGER DEFAULT 0,
    time_mins INTEGER DEFAULT 15,
    category TEXT, -- e.g. 'Breakfast', 'Lunch', etc.
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Diet Templates
CREATE TABLE IF NOT EXISTS public.diet_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    diet_code TEXT NOT NULL UNIQUE,
    diet_name TEXT NOT NULL,
    target TEXT, -- e.g. 'weight_loss', 'weight_gain', 'maintenance'
    food_type TEXT, -- e.g. 'veg', 'non_veg'
    calories_min INTEGER NOT NULL,
    calories_max INTEGER NOT NULL,
    total_weeks INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Meal Library
CREATE TABLE IF NOT EXISTS public.meal_library (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_code TEXT NOT NULL UNIQUE,
    meal_name TEXT NOT NULL,
    meal_type TEXT NOT NULL, -- e.g. 'Breakfast', 'Lunch'
    food_type TEXT DEFAULT 'veg', -- e.g. 'veg', 'non_veg'
    calories INTEGER NOT NULL,
    protein NUMERIC DEFAULT 0,
    carbs NUMERIC DEFAULT 0,
    fat NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Video Series Containers
CREATE TABLE IF NOT EXISTS public.series (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- System Config & Settings
CREATE TABLE IF NOT EXISTS public.system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL, -- e.g., 'true', 'false' or JSON
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Subscription Goals (Signup objectives)
CREATE TABLE IF NOT EXISTS public.subscription_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    icon_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Homepage Banners
CREATE TABLE IF NOT EXISTS public.homepage_banners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT,
    link_url TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Diet Plans (Legacy / Custom User Specific Plans)
CREATE TABLE IF NOT EXISTS public.diet_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    target_calories INTEGER DEFAULT 2000,
    protein_target_pct INTEGER DEFAULT 30,
    carbs_target_pct INTEGER DEFAULT 40,
    fats_target_pct INTEGER DEFAULT 30,
    is_template BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 2. CORE USER MANAGEMENT (Integrates with Supabase Auth)
-- =========================================================================

-- Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    role TEXT DEFAULT 'client', -- 'admin', 'employee', 'client'
    current_weight NUMERIC,
    target_weight NUMERIC,
    height NUMERIC,
    age INTEGER,
    active_plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    active_plan_start_date TIMESTAMPTZ,
    is_subscribed BOOLEAN DEFAULT FALSE,
    subscription_expires_at TIMESTAMPTZ DEFAULT NULL,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Automatically create profile on signup trigger function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'full_name', ''),
        COALESCE(new.raw_user_meta_data->>'role', 'client')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger linking auth.users to public.profiles
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================================
-- 3. SECOND LEVEL TABLES (Dependent on Base Tables & Profiles)
-- =========================================================================

-- Ingredients / Food Items mapping to Meal Library codes
CREATE TABLE IF NOT EXISTS public.meal_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_code TEXT NOT NULL REFERENCES public.meal_library(meal_code) ON DELETE CASCADE,
    food_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Template Schedules (Links Template Code to Meal Code)
CREATE TABLE IF NOT EXISTS public.diet_template_meals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    diet_code TEXT NOT NULL REFERENCES public.diet_templates(diet_code) ON DELETE CASCADE,
    week_no INTEGER NOT NULL,
    day_no INTEGER NOT NULL CHECK (day_no BETWEEN 1 AND 7),
    meal_type TEXT NOT NULL, -- e.g. 'Breakfast', 'Lunch', etc.
    meal_time TEXT NOT NULL, -- Format HH:MM
    meal_code TEXT NOT NULL REFERENCES public.meal_library(meal_code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Diet Plan Schedule (Specific meals in a legacy / custom diet plan)
CREATE TABLE IF NOT EXISTS public.diet_plan_schedule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL REFERENCES public.diet_plans(id) ON DELETE CASCADE,
    meal_category TEXT NOT NULL, -- e.g., 'Breakfast'
    meal_time TEXT NOT NULL,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE SET NULL,
    meal_name TEXT NOT NULL,
    description TEXT,
    calories INTEGER DEFAULT 0,
    quantity NUMERIC DEFAULT 1.0,
    comments TEXT,
    day_of_week INTEGER CHECK (day_of_week BETWEEN 1 AND 7),
    week_number INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Subscription Tiers
CREATE TABLE IF NOT EXISTS public.subscription_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    target_goal TEXT, -- e.g., 'Weight Loss'
    price NUMERIC NOT NULL,
    duration_months INTEGER NOT NULL,
    diet_plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    diet_template_id UUID REFERENCES public.diet_templates(id) ON DELETE SET NULL,
    accessible_weeks INTEGER,
    assignment_mode TEXT DEFAULT 'round_robin', -- 'fixed', 'round_robin'
    fixed_start_week INTEGER,
    target_calories INTEGER DEFAULT 2000,
    is_popular BOOLEAN DEFAULT FALSE,
    features TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Active Meal Schedule
CREATE TABLE IF NOT EXISTS public.user_meal_schedule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    day_index INTEGER NOT NULL, -- Absolute day tracker (e.g. Day 1, 2, 3...)
    meal_time TEXT NOT NULL,
    meal_category TEXT NOT NULL, -- maps to meal_type
    meal_name TEXT NOT NULL,
    calories INTEGER DEFAULT 0,
    quantity NUMERIC DEFAULT 1.0,
    comments TEXT,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Videos ( Bunny CDN upload reference )
CREATE TABLE IF NOT EXISTS public.videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'food', 'news', 'fitness', 'tips'
    is_featured BOOLEAN DEFAULT FALSE,
    duration TEXT, -- 'mm:ss'
    thumbnail_url TEXT,
    video_url TEXT,
    video_type TEXT DEFAULT 'reel', -- 'reel', 'series_episode'
    series_id UUID REFERENCES public.series(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Support Ticket Containers
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'open', -- 'open', 'resolved'
    subject TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 4. LOGS & TRANSACTIONS (Activity logs and payment receipts)
-- =========================================================================

-- Calorie logs
CREATE TABLE IF NOT EXISTS public.calorie_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    food_name TEXT NOT NULL,
    calories INTEGER NOT NULL,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- Hydration logs
CREATE TABLE IF NOT EXISTS public.hydration_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount_ml INTEGER NOT NULL,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meal adherence logs
CREATE TABLE IF NOT EXISTS public.meal_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    schedule_id UUID REFERENCES public.user_meal_schedule(id) ON DELETE SET NULL,
    log_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Razorpay Transactions logs
CREATE TABLE IF NOT EXISTS public.transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    razorpay_payment_id TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    plan_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    status TEXT NOT NULL, -- e.g., 'captured', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chat messages inside support tickets
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL, -- 'admin', 'client'
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Video engagement (likes)
CREATE TABLE IF NOT EXISTS public.video_likes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(video_id, user_id)
);

-- Video engagement (comments)
CREATE TABLE IF NOT EXISTS public.video_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User System Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT DEFAULT 'alert', -- 'alert', 'reminder', 'social', 'achievement'
    is_read BOOLEAN DEFAULT FALSE,
    url TEXT DEFAULT NULL,
    image_url TEXT DEFAULT NULL,
    achievement_id UUID DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Achievements definitions
CREATE TABLE IF NOT EXISTS public.achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    metric_type TEXT NOT NULL, -- 'diet_consistency', 'weight_goal', 'step_streak', 'hydration_streak'
    target_value NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Achievements (Join table)
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    achievement_id UUID NOT NULL REFERENCES public.achievements(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, achievement_id)
);

-- Foreign keys on notifications
ALTER TABLE public.notifications ADD CONSTRAINT fk_notifications_achievement FOREIGN KEY (achievement_id) REFERENCES public.achievements(id) ON DELETE SET NULL;

-- Diet Assignment Linker
CREATE TABLE IF NOT EXISTS public.user_diet_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    subscription_plan_id UUID REFERENCES public.subscription_plans(id) ON DELETE SET NULL,
    diet_template_id UUID REFERENCES public.diet_templates(id) ON DELETE SET NULL,
    weeks_granted INTEGER NOT NULL,
    actual_start_week INTEGER DEFAULT 1,
    actual_end_week INTEGER NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 5. PL/PGSQL RPC FUNCTIONS
-- =========================================================================

-- RPC: assign_user_diet_weeks
-- Records user diet templates assignments based on subscription plans
CREATE OR REPLACE FUNCTION public.assign_user_diet_weeks(
    p_user_id UUID,
    p_subscription_plan_id UUID,
    p_diet_template_id UUID
)
RETURNS JSON AS $$
DECLARE
    v_accessible_weeks INT;
    v_assignment_mode TEXT;
    v_fixed_start_week INT;
    v_total_weeks INT;
    v_start_week INT;
    v_end_week INT;
    v_assignment_id UUID;
    v_duration_months INT;
BEGIN
    -- Get plan details including duration_months
    SELECT accessible_weeks, assignment_mode, fixed_start_week, duration_months
    INTO v_accessible_weeks, v_assignment_mode, v_fixed_start_week, v_duration_months
    FROM public.subscription_plans
    WHERE id = p_subscription_plan_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object('error', 'Subscription plan not found');
    END IF;
    
    -- Get template details
    SELECT total_weeks
    INTO v_total_weeks
    FROM public.diet_templates
    WHERE id = p_diet_template_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object('error', 'Diet template not found');
    END IF;
    
    -- Determine start week
    IF v_assignment_mode = 'fixed' THEN
        v_start_week := COALESCE(v_fixed_start_week, 1);
    ELSE
        v_start_week := 1;
    END IF;
    
    -- Determine end week
    v_end_week := v_start_week + COALESCE(v_accessible_weeks, v_total_weeks) - 1;
    
    -- Insert assignment
    INSERT INTO public.user_diet_assignments (
        user_id,
        subscription_plan_id,
        diet_template_id,
        weeks_granted,
        actual_start_week,
        actual_end_week,
        assigned_at
    ) VALUES (
        p_user_id,
        p_subscription_plan_id,
        p_diet_template_id,
        COALESCE(v_accessible_weeks, v_total_weeks),
        v_start_week,
        v_end_week,
        NOW()
    )
    RETURNING id INTO v_assignment_id;

    -- Update profile subscription details and expiry
    UPDATE public.profiles
    SET is_subscribed = true,
        subscription_expires_at = NOW() + (COALESCE(v_duration_months, 1) * INTERVAL '1 month')
    WHERE id = p_user_id;
    
    RETURN json_build_object(
        'success', true,
        'assignment_id', v_assignment_id,
        'weeks_granted', COALESCE(v_accessible_weeks, v_total_weeks),
        'actual_start_week', v_start_week,
        'actual_end_week', v_end_week
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: generate_user_schedule
-- Populates user_meal_schedule dynamically from template meals range
CREATE OR REPLACE FUNCTION public.generate_user_schedule(p_user_id UUID)
RETURNS JSON AS $$
DECLARE
    v_assignment RECORD;
    v_plan_id UUID;
    v_inserted_count INT;
    v_weeks_generated INT;
BEGIN
    -- Get latest assignment details
    SELECT a.*, t.diet_code
    INTO v_assignment
    FROM public.user_diet_assignments a
    JOIN public.diet_templates t ON a.diet_template_id = t.id
    WHERE a.user_id = p_user_id
    ORDER BY a.assigned_at DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN json_build_object('error', 'No active diet assignment found for user');
    END IF;

    -- Find or create client-specific diet plan
    SELECT id INTO v_plan_id
    FROM public.diet_plans
    WHERE name = 'User Plan - ' || p_user_id
    LIMIT 1;

    IF NOT FOUND THEN
        INSERT INTO public.diet_plans (
            name,
            description,
            is_template,
            created_at
        ) VALUES (
            'User Plan - ' || p_user_id,
            'Auto-generated plan from template',
            false,
            NOW()
        )
        RETURNING id INTO v_plan_id;
    END IF;

    -- Clear existing schedules
    DELETE FROM public.user_meal_schedule
    WHERE user_id = p_user_id;

    -- Insert meals from template range
    INSERT INTO public.user_meal_schedule (
        user_id,
        plan_id,
        day_index,
        meal_time,
        meal_category,
        meal_name,
        calories,
        quantity,
        comments
    )
    SELECT
        p_user_id,
        v_plan_id,
        (tm.week_no - v_assignment.actual_start_week) * 7 + tm.day_no,
        tm.meal_time,
        tm.meal_type,
        COALESCE(ml.meal_name, ''),
        COALESCE(ml.calories, 0),
        1.0,
        'From template: ' || tm.diet_code || ' Week ' || tm.week_no
    FROM public.diet_template_meals tm
    LEFT JOIN public.meal_library ml ON tm.meal_code = ml.meal_code
    WHERE tm.diet_code = v_assignment.diet_code
      AND tm.week_no >= v_assignment.actual_start_week
      AND tm.week_no <= v_assignment.actual_end_week;

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

    -- Calculate count of weeks
    v_weeks_generated := v_assignment.actual_end_week - v_assignment.actual_start_week + 1;

    -- Update active plan details on user profile
    UPDATE public.profiles
    SET active_plan_id = v_plan_id,
        active_plan_start_date = NOW()
    WHERE id = p_user_id;

    RETURN json_build_object(
        'success', true,
        'weeks_generated', v_weeks_generated,
        'meals_inserted', v_inserted_count
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =========================================================================
-- 6. INDEXES FOR PERFORMANCE
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_profiles_active_plan ON public.profiles(active_plan_id);
CREATE INDEX IF NOT EXISTS idx_diet_plan_schedule_plan ON public.diet_plan_schedule(plan_id);
CREATE INDEX IF NOT EXISTS idx_meal_items_meal_code ON public.meal_items(meal_code);
CREATE INDEX IF NOT EXISTS idx_diet_template_meals_code ON public.diet_template_meals(diet_code);
CREATE INDEX IF NOT EXISTS idx_user_meal_schedule_user ON public.user_meal_schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_user_diet_assignments_user ON public.user_diet_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_calorie_logs_user ON public.calorie_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_hydration_logs_user ON public.hydration_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_meal_logs_user ON public.meal_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_ticket ON public.chat_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user ON public.support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_videos_series ON public.videos(series_id);
CREATE INDEX IF NOT EXISTS idx_video_likes_video ON public.video_likes(video_id);
CREATE INDEX IF NOT EXISTS idx_video_comments_video ON public.video_comments(video_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_achievement ON public.notifications(achievement_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON public.user_achievements(user_id);

-- =========================================================================
-- 6a. AUTOMATIC TRIGGER FUNCTIONS FOR ACHIEVEMENTS & REMINDERS
-- =========================================================================

-- Evaluate User Achievements Function
CREATE OR REPLACE FUNCTION public.evaluate_user_achievements(p_user_id UUID)
RETURNS VOID AS $$
DECLARE
    v_achievement RECORD;
    v_eligible BOOLEAN;
    v_count INT;
    v_profile RECORD;
BEGIN
    SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    FOR v_achievement IN 
        SELECT * FROM public.achievements WHERE is_active = TRUE
    LOOP
        IF EXISTS (
            SELECT 1 FROM public.user_achievements 
            WHERE user_id = p_user_id AND achievement_id = v_achievement.id
        ) THEN
            CONTINUE;
        END IF;

        v_eligible := FALSE;

        IF v_achievement.metric_type = 'diet_consistency' THEN
            SELECT COUNT(DISTINCT log_date::date) INTO v_count FROM public.meal_logs
            WHERE user_id = p_user_id
              AND log_date >= CURRENT_DATE - (v_achievement.target_value::integer - 1) * INTERVAL '1 day';
            IF v_count >= v_achievement.target_value::integer THEN v_eligible := TRUE; END IF;

        ELSIF v_achievement.metric_type = 'weight_goal' THEN
            IF v_profile.target_weight IS NOT NULL AND v_profile.current_weight IS NOT NULL THEN
                IF ABS(v_profile.current_weight - v_profile.target_weight) <= 0.2 THEN
                    v_eligible := TRUE;
                END IF;
            END IF;

        ELSIF v_achievement.metric_type = 'step_streak' THEN
            SELECT COUNT(DISTINCT step_date) INTO v_count FROM public.step_logs
            WHERE user_id = p_user_id AND total_steps >= goal_steps
              AND step_date >= CURRENT_DATE - (v_achievement.target_value::integer - 1) * INTERVAL '1 day';
            IF v_count >= v_achievement.target_value::integer THEN v_eligible := TRUE; END IF;

        ELSIF v_achievement.metric_type = 'hydration_streak' THEN
            SELECT COUNT(DISTINCT logged_at::date) INTO v_count FROM public.hydration_logs
            WHERE user_id = p_user_id
              AND logged_at >= CURRENT_DATE - (v_achievement.target_value::integer - 1) * INTERVAL '1 day';
            IF v_count >= v_achievement.target_value::integer THEN v_eligible := TRUE; END IF;
        END IF;

        IF v_eligible THEN
            INSERT INTO public.user_achievements (user_id, achievement_id) VALUES (p_user_id, v_achievement.id) ON CONFLICT DO NOTHING;
            INSERT INTO public.notifications (user_id, title, description, type, achievement_id)
            VALUES (p_user_id, v_achievement.title, v_achievement.description, 'achievement', v_achievement.id);
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger functions for log updates
CREATE OR REPLACE FUNCTION public.trg_evaluate_achievements_meal() RETURNS TRIGGER AS $$
BEGIN PERFORM public.evaluate_user_achievements(NEW.user_id); RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_after_meal_log_insert AFTER INSERT ON public.meal_logs FOR EACH ROW EXECUTE FUNCTION public.trg_evaluate_achievements_meal();

CREATE OR REPLACE FUNCTION public.trg_evaluate_achievements_hydration() RETURNS TRIGGER AS $$
BEGIN PERFORM public.evaluate_user_achievements(NEW.user_id); RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_after_hydration_log_insert AFTER INSERT ON public.hydration_logs FOR EACH ROW EXECUTE FUNCTION public.trg_evaluate_achievements_hydration();

CREATE OR REPLACE FUNCTION public.trg_evaluate_achievements_steps() RETURNS TRIGGER AS $$
BEGIN PERFORM public.evaluate_user_achievements(NEW.user_id); RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_after_step_log_insert AFTER INSERT OR UPDATE OF total_steps ON public.step_logs FOR EACH ROW EXECUTE FUNCTION public.trg_evaluate_achievements_steps();

CREATE OR REPLACE FUNCTION public.trg_evaluate_achievements_weight() RETURNS TRIGGER AS $$
BEGIN IF OLD.current_weight IS DISTINCT FROM NEW.current_weight THEN PERFORM public.evaluate_user_achievements(NEW.id); END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_after_profile_weight_update AFTER UPDATE OF current_weight ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.trg_evaluate_achievements_weight();

-- Payment Reminders check function
CREATE OR REPLACE FUNCTION public.check_and_send_payment_reminders()
RETURNS VOID AS $$
DECLARE
    v_user RECORD;
    v_days_left INT;
BEGIN
    FOR v_user IN
        SELECT id, email, full_name, subscription_expires_at FROM public.profiles
        WHERE is_subscribed = TRUE AND subscription_expires_at IS NOT NULL AND subscription_expires_at > NOW() AND subscription_expires_at - NOW() <= INTERVAL '3 days'
    LOOP
        v_days_left := CEIL(EXTRACT(epoch FROM (v_user.subscription_expires_at - NOW())) / 86400)::integer;
        IF NOT EXISTS (
            SELECT 1 FROM public.notifications
            WHERE user_id = v_user.id AND type = 'reminder' AND title = '💳 Subscription Expiry Reminder' AND created_at >= NOW() - INTERVAL '20 hours'
        ) THEN
            INSERT INTO public.notifications (user_id, title, description, type)
            VALUES (v_user.id, '💳 Subscription Expiry Reminder', 'Hi ' || COALESCE(v_user.full_name, 'there') || ', your subscription plan expires in ' || v_days_left || ' days. Renew now to avoid interruption in your service!', 'reminder');
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Diet Reminders check function (Upcoming & Missed Meals)
CREATE OR REPLACE FUNCTION public.check_and_send_diet_reminders()
RETURNS VOID AS $$
DECLARE
    v_diet_setting JSONB;
    v_user RECORD;
    v_meal RECORD;
    v_day_index INT;
    v_meal_time_val TIME;
    v_curr_time TIME;
    v_diff_seconds INT;
    v_upcoming_sent BOOLEAN;
    v_missed_sent BOOLEAN;
    v_is_logged BOOLEAN;
BEGIN
    -- Get diet automation settings
    BEGIN 
        SELECT value::jsonb INTO v_diet_setting 
        FROM public.system_settings 
        WHERE key = 'diet_automation'; 
    EXCEPTION WHEN OTHERS THEN 
        v_diet_setting := NULL; 
    END;

    -- If disabled or not found, exit
    IF v_diet_setting IS NULL OR (v_diet_setting->>'enabled')::boolean = FALSE THEN
        RETURN;
    END IF;

    -- Current local time in Asia/Kolkata
    v_curr_time := (NOW() AT TIME ZONE 'Asia/Kolkata')::TIME;

    FOR v_user IN 
        SELECT id, active_plan_start_date 
        FROM public.profiles 
        WHERE active_plan_id IS NOT NULL AND active_plan_start_date IS NOT NULL
    LOOP
        -- Calculate current day index (1-based)
        v_day_index := FLOOR(EXTRACT(EPOCH FROM (NOW() - v_user.active_plan_start_date)) / 86400) + 1;

        -- Loop through scheduled meals for the user on this day
        FOR v_meal IN 
            SELECT id, meal_time, meal_category, meal_name 
            FROM public.user_meal_schedule 
            WHERE user_id = v_user.id AND day_index = v_day_index
        LOOP
            -- Parse meal_time
            BEGIN
                IF v_meal.meal_time LIKE '%AM%' OR v_meal.meal_time LIKE '%PM%' THEN
                    v_meal_time_val := TO_TIMESTAMP(v_meal.meal_time, 'HH12:MI AM')::TIME;
                ELSE
                    v_meal_time_val := TO_TIMESTAMP(v_meal.meal_time, 'HH24:MI')::TIME;
                END IF;
            EXCEPTION WHEN OTHERS THEN
                v_meal_time_val := NULL;
            END;

            IF v_meal_time_val IS NOT NULL THEN
                -- Calculate time difference in seconds
                v_diff_seconds := EXTRACT(EPOCH FROM (v_meal_time_val - v_curr_time));

                -- CASE 1: Upcoming meal (Scheduled in next 30 minutes, i.e., diff between 0 and 1800 seconds)
                IF v_diff_seconds >= 0 AND v_diff_seconds <= 1800 THEN
                    -- Check if already sent
                    SELECT EXISTS(
                        SELECT 1 FROM public.notifications 
                        WHERE user_id = v_user.id 
                          AND title = '🍽️ Upcoming Meal: ' || v_meal.meal_category 
                          AND created_at >= NOW() - INTERVAL '12 hours'
                    ) INTO v_upcoming_sent;

                    IF NOT v_upcoming_sent THEN
                        INSERT INTO public.notifications (user_id, title, description, type)
                        VALUES (
                            v_user.id, 
                            '🍽️ Upcoming Meal: ' || v_meal.meal_category, 
                            'Your scheduled ' || v_meal.meal_category || ' (' || v_meal.meal_name || ') is coming up at ' || v_meal.meal_time || '. Get ready!', 
                            'reminder'
                        );
                    END IF;

                -- CASE 2: Missed meal (Scheduled in past, between 30 minutes and 3 hours ago, i.e., diff between -10800 and -1800 seconds)
                ELSIF v_diff_seconds >= -10800 AND v_diff_seconds <= -1800 THEN
                    -- Check if user logged it
                    SELECT EXISTS(
                        SELECT 1 FROM public.meal_logs 
                        WHERE user_id = v_user.id 
                          AND schedule_id = v_meal.id
                    ) INTO v_is_logged;

                    IF NOT v_is_logged THEN
                        -- Check if reminder already sent
                        SELECT EXISTS(
                            SELECT 1 FROM public.notifications 
                            WHERE user_id = v_user.id 
                              AND title = '⚠️ Missed Meal: ' || v_meal.meal_category 
                              AND created_at >= NOW() - INTERVAL '12 hours'
                        ) INTO v_missed_sent;

                        IF NOT v_missed_sent THEN
                            INSERT INTO public.notifications (user_id, title, description, type)
                            VALUES (
                                v_user.id, 
                                '⚠️ Missed Meal: ' || v_meal.meal_category, 
                                'It looks like you missed logging your ' || v_meal.meal_category || ' (' || v_meal.meal_name || ') scheduled at ' || v_meal.meal_time || '. Please update your log!', 
                                'reminder'
                            );
                        END IF;
                    END IF;
                END IF;
            END IF;
        END LOOP;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Automated Reminders check function
CREATE OR REPLACE FUNCTION public.check_and_send_automated_reminders()
RETURNS VOID AS $$
DECLARE
    v_water_setting JSONB;
    v_steps_setting JSONB;
    v_last_water_sent TIMESTAMPTZ;
    v_last_steps_sent TIMESTAMPTZ;
    v_user RECORD;
BEGIN
    BEGIN SELECT value::jsonb INTO v_water_setting FROM public.system_settings WHERE key = 'water_automation'; EXCEPTION WHEN OTHERS THEN v_water_setting := NULL; END;
    BEGIN SELECT value::jsonb INTO v_steps_setting FROM public.system_settings WHERE key = 'steps_automation'; EXCEPTION WHEN OTHERS THEN v_steps_setting := NULL; END;

    IF v_water_setting IS NOT NULL AND (v_water_setting->>'enabled')::boolean = TRUE THEN
        SELECT MAX(created_at) INTO v_last_water_sent FROM public.notifications WHERE type = 'reminder' AND title = '💧 Hydration Check';
        IF v_last_water_sent IS NULL OR NOW() - v_last_water_sent >= (v_water_setting->>'interval_hours')::integer * INTERVAL '1 hour' THEN
            FOR v_user IN SELECT id FROM public.profiles LOOP
                INSERT INTO public.notifications (user_id, title, description, type)
                VALUES (v_user.id, '💧 Hydration Check', 'You''re doing great! Don''t forget to log your next glass of water to keep your streak alive.', 'reminder');
            END LOOP;
        END IF;
    END IF;

    IF v_steps_setting IS NOT NULL AND (v_steps_setting->>'enabled')::boolean = TRUE THEN
        SELECT MAX(created_at) INTO v_last_steps_sent FROM public.notifications WHERE type = 'reminder' AND title = '🏃 Step Goal Update';
        IF v_last_steps_sent IS NULL OR NOW() - v_last_steps_sent >= (v_steps_setting->>'interval_hours')::integer * INTERVAL '1 hour' THEN
            FOR v_user IN SELECT id FROM public.profiles LOOP
                INSERT INTO public.notifications (user_id, title, description, type)
                VALUES (v_user.id, '🏃 Step Goal Update', 'How are your steps looking? A short walk can help you reach your daily goal!', 'reminder');
            END LOOP;
        END IF;
    END IF;

    -- Call diet reminders
    PERFORM public.check_and_send_diet_reminders();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Seed default achievements
INSERT INTO public.achievements (title, description, metric_type, target_value)
SELECT '🏆 1-Week Diet Streak', 'Adhered to your diet plan for 7 consecutive days!', 'diet_consistency', 7
WHERE NOT EXISTS (SELECT 1 FROM public.achievements WHERE title = '🏆 1-Week Diet Streak');

INSERT INTO public.achievements (title, description, metric_type, target_value)
SELECT '⚖️ Weight Target Reached', 'Congratulations! You achieved your target weight goal!', 'weight_goal', 1
WHERE NOT EXISTS (SELECT 1 FROM public.achievements WHERE title = '⚖️ Weight Target Reached');

INSERT INTO public.achievements (title, description, metric_type, target_value)
SELECT '🏃 Walk-a-Thon Master', 'Completed your step goal for 7 consecutive days!', 'step_streak', 7
WHERE NOT EXISTS (SELECT 1 FROM public.achievements WHERE title = '🏃 Walk-a-Thon Master');

INSERT INTO public.achievements (title, description, metric_type, target_value)
SELECT '💧 Aqua Champion', 'Logged your hydration for 7 consecutive days!', 'hydration_streak', 7
WHERE NOT EXISTS (SELECT 1 FROM public.achievements WHERE title = '💧 Aqua Champion');

-- =========================================================================
-- 7. REQUIRED BUCKET REFERENCES (STORAGE)
-- =========================================================================
-- Ensure to create these storage buckets inside the Supabase Console:
-- 1. "banner-images" (Public) - For homepage promotion banners
-- 2. "thumbnails" (Public) - For Reel cover images
-- 3. "videos" (Public) - For Reel video files
-- 4. "video-thumbnails" (Public) - For Series header/thumbnail photos
