-- Supabase Database Schema Script for DietWise
-- Run this script in the Supabase SQL Editor.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. BASE TABLES (No Foreign Key Dependencies)
-- =========================================================================

-- Recipes Global Library
CREATE TABLE IF NOT EXISTS public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    ingredients TEXT,
    instructions TEXT,
    calories INTEGER DEFAULT 0,
    protein_g INTEGER DEFAULT 0,
    carbs_g INTEGER DEFAULT 0,
    fats_g INTEGER DEFAULT 0,
    time_mins INTEGER DEFAULT 15,
    category TEXT, -- e.g. 'Breakfast', 'Lunch', etc.
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Diet Templates
CREATE TABLE IF NOT EXISTS public.diet_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    diet_code TEXT NOT NULL UNIQUE,
    diet_name TEXT NOT NULL,
    target TEXT, -- e.g. 'weight_loss', 'weight_gain', 'maintenance'
    food_type TEXT, -- e.g. 'veg', 'non_veg'
    calories_min INTEGER NOT NULL,
    calories_max INTEGER NOT NULL,
    total_weeks INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Meal Library
CREATE TABLE IF NOT EXISTS public.meal_library (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_code TEXT NOT NULL UNIQUE,
    meal_name TEXT NOT NULL,
    meal_type TEXT NOT NULL, -- e.g. 'Breakfast', 'Lunch'
    food_type TEXT DEFAULT 'veg', -- e.g. 'veg', 'non_veg'
    calories INTEGER NOT NULL,
    protein NUMERIC DEFAULT 0,
    carbs NUMERIC DEFAULT 0,
    fat NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Video Series Containers
CREATE TABLE IF NOT EXISTS public.series (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- System Config & Settings
CREATE TABLE IF NOT EXISTS public.system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL, -- e.g., 'true', 'false' or JSON
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Subscription Goals (Signup objectives)
CREATE TABLE IF NOT EXISTS public.subscription_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    icon_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Homepage Banners
CREATE TABLE IF NOT EXISTS public.homepage_banners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    subtitle TEXT,
    image_url TEXT,
    link_url TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Diet Plans (Legacy / Custom User Specific Plans)
CREATE TABLE IF NOT EXISTS public.diet_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    target_calories INTEGER DEFAULT 2000,
    protein_target_pct INTEGER DEFAULT 30,
    carbs_target_pct INTEGER DEFAULT 40,
    fats_target_pct INTEGER DEFAULT 30,
    is_template BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 2. CORE USER MANAGEMENT (Integrates with Supabase Auth)
-- =========================================================================

-- Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    role TEXT DEFAULT 'client', -- 'admin', 'employee', 'client'
    current_weight NUMERIC,
    target_weight NUMERIC,
    height NUMERIC,
    age INTEGER,
    active_plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    active_plan_start_date TIMESTAMPTZ,
    is_subscribed BOOLEAN DEFAULT FALSE,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Automatically create profile on signup trigger function
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'full_name', ''),
        COALESCE(new.raw_user_meta_data->>'role', 'client')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger linking auth.users to public.profiles
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================================
-- 3. SECOND LEVEL TABLES (Dependent on Base Tables & Profiles)
-- =========================================================================

-- Ingredients / Food Items mapping to Meal Library codes
CREATE TABLE IF NOT EXISTS public.meal_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_code TEXT NOT NULL REFERENCES public.meal_library(meal_code) ON DELETE CASCADE,
    food_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Master Template Schedules (Links Template Code to Meal Code)
CREATE TABLE IF NOT EXISTS public.diet_template_meals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    diet_code TEXT NOT NULL REFERENCES public.diet_templates(diet_code) ON DELETE CASCADE,
    week_no INTEGER NOT NULL,
    day_no INTEGER NOT NULL CHECK (day_no BETWEEN 1 AND 7),
    meal_type TEXT NOT NULL, -- e.g. 'Breakfast', 'Lunch', etc.
    meal_time TEXT NOT NULL, -- Format HH:MM
    meal_code TEXT NOT NULL REFERENCES public.meal_library(meal_code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Diet Plan Schedule (Specific meals in a legacy / custom diet plan)
CREATE TABLE IF NOT EXISTS public.diet_plan_schedule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL REFERENCES public.diet_plans(id) ON DELETE CASCADE,
    meal_category TEXT NOT NULL, -- e.g., 'Breakfast'
    meal_time TEXT NOT NULL,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE SET NULL,
    meal_name TEXT NOT NULL,
    description TEXT,
    calories INTEGER DEFAULT 0,
    quantity NUMERIC DEFAULT 1.0,
    comments TEXT,
    day_of_week INTEGER CHECK (day_of_week BETWEEN 1 AND 7),
    week_number INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Subscription Tiers
CREATE TABLE IF NOT EXISTS public.subscription_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    target_goal TEXT, -- e.g., 'Weight Loss'
    price NUMERIC NOT NULL,
    duration_months INTEGER NOT NULL,
    diet_plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    diet_template_id UUID REFERENCES public.diet_templates(id) ON DELETE SET NULL,
    accessible_weeks INTEGER,
    assignment_mode TEXT DEFAULT 'round_robin', -- 'fixed', 'round_robin'
    fixed_start_week INTEGER,
    target_calories INTEGER DEFAULT 2000,
    is_popular BOOLEAN DEFAULT FALSE,
    features TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Active Meal Schedule
CREATE TABLE IF NOT EXISTS public.user_meal_schedule (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES public.diet_plans(id) ON DELETE SET NULL,
    day_index INTEGER NOT NULL, -- Absolute day tracker (e.g. Day 1, 2, 3...)
    meal_time TEXT NOT NULL,
    meal_category TEXT NOT NULL, -- maps to meal_type
    meal_name TEXT NOT NULL,
    calories INTEGER DEFAULT 0,
    quantity NUMERIC DEFAULT 1.0,
    comments TEXT,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Videos ( Bunny CDN upload reference )
CREATE TABLE IF NOT EXISTS public.videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'food', 'news', 'fitness', 'tips'
    is_featured BOOLEAN DEFAULT FALSE,
    duration TEXT, -- 'mm:ss'
    thumbnail_url TEXT,
    video_url TEXT,
    video_type TEXT DEFAULT 'reel', -- 'reel', 'series_episode'
    series_id UUID REFERENCES public.series(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Support Ticket Containers
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'open', -- 'open', 'resolved'
    subject TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 4. LOGS & TRANSACTIONS (Activity logs and payment receipts)
-- =========================================================================

-- Calorie logs
CREATE TABLE IF NOT EXISTS public.calorie_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    food_name TEXT NOT NULL,
    calories INTEGER NOT NULL,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- Hydration logs
CREATE TABLE IF NOT EXISTS public.hydration_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount_ml INTEGER NOT NULL,
    logged_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meal adherence logs
CREATE TABLE IF NOT EXISTS public.meal_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    schedule_id UUID REFERENCES public.user_meal_schedule(id) ON DELETE SET NULL,
    log_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Razorpay Transactions logs
CREATE TABLE IF NOT EXISTS public.transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    razorpay_payment_id TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    plan_name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    status TEXT NOT NULL, -- e.g., 'captured', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chat messages inside support tickets
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    sender_type TEXT NOT NULL, -- 'admin', 'client'
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Video engagement (likes)
CREATE TABLE IF NOT EXISTS public.video_likes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(video_id, user_id)
);

-- Video engagement (comments)
CREATE TABLE IF NOT EXISTS public.video_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User System Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT DEFAULT 'alert', -- 'alert', 'reminder'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Diet Assignment Linker
CREATE TABLE IF NOT EXISTS public.user_diet_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    subscription_plan_id UUID REFERENCES public.subscription_plans(id) ON DELETE SET NULL,
    diet_template_id UUID REFERENCES public.diet_templates(id) ON DELETE SET NULL,
    weeks_granted INTEGER NOT NULL,
    actual_start_week INTEGER DEFAULT 1,
    actual_end_week INTEGER NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- 5. PL/PGSQL RPC FUNCTIONS
-- =========================================================================

-- RPC: assign_user_diet_weeks
-- Records user diet templates assignments based on subscription plans
CREATE OR REPLACE FUNCTION public.assign_user_diet_weeks(
    p_user_id UUID,
    p_subscription_plan_id UUID,
    p_diet_template_id UUID
)
RETURNS JSON AS $$
DECLARE
    v_accessible_weeks INT;
    v_assignment_mode TEXT;
    v_fixed_start_week INT;
    v_total_weeks INT;
    v_start_week INT;
    v_end_week INT;
    v_assignment_id UUID;
BEGIN
    -- Get plan details
    SELECT accessible_weeks, assignment_mode, fixed_start_week
    INTO v_accessible_weeks, v_assignment_mode, v_fixed_start_week
    FROM public.subscription_plans
    WHERE id = p_subscription_plan_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object('error', 'Subscription plan not found');
    END IF;
    
    -- Get template details
    SELECT total_weeks
    INTO v_total_weeks
    FROM public.diet_templates
    WHERE id = p_diet_template_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object('error', 'Diet template not found');
    END IF;
    
    -- Determine start week
    IF v_assignment_mode = 'fixed' THEN
        v_start_week := COALESCE(v_fixed_start_week, 1);
    ELSE
        v_start_week := 1;
    END IF;
    
    -- Determine end week
    v_end_week := v_start_week + COALESCE(v_accessible_weeks, v_total_weeks) - 1;
    
    -- Insert assignment
    INSERT INTO public.user_diet_assignments (
        user_id,
        subscription_plan_id,
        diet_template_id,
        weeks_granted,
        actual_start_week,
        actual_end_week,
        assigned_at
    ) VALUES (
        p_user_id,
        p_subscription_plan_id,
        p_diet_template_id,
        COALESCE(v_accessible_weeks, v_total_weeks),
        v_start_week,
        v_end_week,
        NOW()
    )
    RETURNING id INTO v_assignment_id;
    
    RETURN json_build_object(
        'success', true,
        'assignment_id', v_assignment_id,
        'weeks_granted', COALESCE(v_accessible_weeks, v_total_weeks),
        'actual_start_week', v_start_week,
        'actual_end_week', v_end_week
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC: generate_user_schedule
-- Populates user_meal_schedule dynamically from template meals range
CREATE OR REPLACE FUNCTION public.generate_user_schedule(p_user_id UUID)
RETURNS JSON AS $$
DECLARE
    v_assignment RECORD;
    v_plan_id UUID;
    v_inserted_count INT;
    v_weeks_generated INT;
BEGIN
    -- Get latest assignment details
    SELECT a.*, t.diet_code
    INTO v_assignment
    FROM public.user_diet_assignments a
    JOIN public.diet_templates t ON a.diet_template_id = t.id
    WHERE a.user_id = p_user_id
    ORDER BY a.assigned_at DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN json_build_object('error', 'No active diet assignment found for user');
    END IF;

    -- Find or create client-specific diet plan
    SELECT id INTO v_plan_id
    FROM public.diet_plans
    WHERE name = 'User Plan - ' || p_user_id
    LIMIT 1;

    IF NOT FOUND THEN
        INSERT INTO public.diet_plans (
            name,
            description,
            is_template,
            created_at
        ) VALUES (
            'User Plan - ' || p_user_id,
            'Auto-generated plan from template',
            false,
            NOW()
        )
        RETURNING id INTO v_plan_id;
    END IF;

    -- Clear existing schedules
    DELETE FROM public.user_meal_schedule
    WHERE user_id = p_user_id;

    -- Insert meals from template range
    INSERT INTO public.user_meal_schedule (
        user_id,
        plan_id,
        day_index,
        meal_time,
        meal_category,
        meal_name,
        calories,
        quantity,
        comments
    )
    SELECT
        p_user_id,
        v_plan_id,
        (tm.week_no - v_assignment.actual_start_week) * 7 + tm.day_no,
        tm.meal_time,
        tm.meal_type,
        COALESCE(ml.meal_name, ''),
        COALESCE(ml.calories, 0),
        1.0,
        'From template: ' || tm.diet_code || ' Week ' || tm.week_no
    FROM public.diet_template_meals tm
    LEFT JOIN public.meal_library ml ON tm.meal_code = ml.meal_code
    WHERE tm.diet_code = v_assignment.diet_code
      AND tm.week_no >= v_assignment.actual_start_week
      AND tm.week_no <= v_assignment.actual_end_week;

    GET DIAGNOSTICS v_inserted_count = ROW_COUNT;

    -- Calculate count of weeks
    v_weeks_generated := v_assignment.actual_end_week - v_assignment.actual_start_week + 1;

    -- Update active plan details on user profile
    UPDATE public.profiles
    SET active_plan_id = v_plan_id,
        active_plan_start_date = NOW()
    WHERE id = p_user_id;

    RETURN json_build_object(
        'success', true,
        'weeks_generated', v_weeks_generated,
        'meals_inserted', v_inserted_count
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =========================================================================
-- 6. INDEXES FOR PERFORMANCE
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_profiles_active_plan ON public.profiles(active_plan_id);
CREATE INDEX IF NOT EXISTS idx_diet_plan_schedule_plan ON public.diet_plan_schedule(plan_id);
CREATE INDEX IF NOT EXISTS idx_meal_items_meal_code ON public.meal_items(meal_code);
CREATE INDEX IF NOT EXISTS idx_diet_template_meals_code ON public.diet_template_meals(diet_code);
CREATE INDEX IF NOT EXISTS idx_user_meal_schedule_user ON public.user_meal_schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_user_diet_assignments_user ON public.user_diet_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_calorie_logs_user ON public.calorie_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_hydration_logs_user ON public.hydration_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_meal_logs_user ON public.meal_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_ticket ON public.chat_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user ON public.support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_videos_series ON public.videos(series_id);
CREATE INDEX IF NOT EXISTS idx_video_likes_video ON public.video_likes(video_id);
CREATE INDEX IF NOT EXISTS idx_video_comments_video ON public.video_comments(video_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);

-- =========================================================================
-- 7. REQUIRED BUCKET REFERENCES (STORAGE)
-- =========================================================================
-- Ensure to create these storage buckets inside the Supabase Console:
-- 1. "banner-images" (Public) - For homepage promotion banners
-- 2. "thumbnails" (Public) - For Reel cover images
-- 3. "videos" (Public) - For Reel video files
-- 4. "video-thumbnails" (Public) - For Series header/thumbnail photos
